import asyncio
import sys
import os

# Add backend to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from llm.groq import GroqProvider
from services.interview_planner import generate_interview_plan
from services.answer_evaluator import evaluate_answer
from services.question_generator import generate_next_question
from schemas import InterviewPlan, AnswerEvaluation, InterviewSession

async def simulate_interview(test_name, resume, jd, interview_type, difficulty, answers):
    print(f"\n{'='*60}")
    print(f"RUNNING SIMULATION: {test_name}")
    print(f"{'='*60}")
    
    llm = GroqProvider()
    
    # 1. PLANNER
    print("\n--- PHASE 1: PLANNING ---")
    plan_data = await generate_interview_plan(llm, resume, jd, interview_type, difficulty)
    plan = InterviewPlan(**plan_data)
    print(f"Skills to test: {plan.skills_to_test}")
    print(f"Topic Order: {plan.topic_order}")
    print(f"Difficulty Strategy: {plan.difficulty_strategy}")
    
    # Initialize Session Mock
    session = InterviewSession(
        session_id="test_sim_123",
        start_timestamp=0.0,
        total_duration_minutes=30,
        interview_type=interview_type,
        difficulty=difficulty,
        plan=plan
    )
    
    # Starting Question (Mocked for testing since /start uses old logic still)
    current_topic = plan.topic_order[0]
    session.current_topic = current_topic
    
    session.follow_up_depth = 0
    
    # Starting Question generated by Question Generator
    latest_question = await generate_next_question(
        llm=llm,
        current_topic=session.current_topic,
        latest_question="",
        candidate_answer="",
        evaluation_results=None,
        difficulty=difficulty,
        is_follow_up=False
    )
        
    print(f"\n[INTERVIEWER]: {latest_question}")
    
    # Iterating over answers
    for idx, ans in enumerate(answers):
        print(f"\n[CANDIDATE]: {ans}")
        
        # 2. EVALUATOR
        print("\n  --- PHASE 2: EVALUATION ---")
        eval_data = await evaluate_answer(
            llm=llm,
            latest_question=latest_question,
            candidate_answer=ans,
            current_topic=session.current_topic,
            interview_type=interview_type,
            difficulty=difficulty
        )
        session.last_evaluation = AnswerEvaluation(**eval_data)
        print(f"  Quality: {session.last_evaluation.answer_quality}")
        print(f"  Follow-up Required: {session.last_evaluation.follow_up_required}")
        print(f"  Missing: {session.last_evaluation.missing_concepts}")
        print(f"  Diff Adj: {session.last_evaluation.difficulty_adjustment}")
        
        # 3. DECISION ENGINE
        is_follow_up = False
        MAX_FOLLOW_UP_DEPTH = 3
        
        if session.last_evaluation.follow_up_required and session.follow_up_depth < MAX_FOLLOW_UP_DEPTH:
            session.follow_up_depth += 1
            is_follow_up = True
            print(f"  [DECISION]: Stay on '{session.current_topic}', Follow-up depth: {session.follow_up_depth}")
        else:
            if session.follow_up_depth >= MAX_FOLLOW_UP_DEPTH:
                print(f"  [DECISION]: FORCE NEXT TOPIC (Max depth {MAX_FOLLOW_UP_DEPTH} reached)")
                
            session.current_topic_index += 1
            if session.current_topic_index < len(plan.topic_order):
                session.current_topic = plan.topic_order[session.current_topic_index]
                print(f"  [DECISION]: Move to next topic: '{session.current_topic}'")
            else:
                session.current_topic = "General Wrap-up"
                print(f"  [DECISION]: Roadmap complete, fallback to: '{session.current_topic}'")
            session.follow_up_depth = 0
            is_follow_up = False
            
        # 4. QUESTION GENERATION
        next_q = await generate_next_question(
            llm=llm,
            current_topic=session.current_topic,
            latest_question=latest_question,
            candidate_answer=ans,
            evaluation_results=session.last_evaluation.model_dump(),
            difficulty=difficulty,
            is_follow_up=is_follow_up
        )
        
        latest_question = next_q
        print(f"\n[INTERVIEWER]: {latest_question}")

async def main():
    # TEST CASE 1: WEAK TECHNICAL CANDIDATE
    await simulate_interview(
        "WEAK TECHNICAL CANDIDATE",
        "Frontend Intern. React, HTML, JS",
        "Frontend Internship",
        "Technical",
        "Medium",
        [
            "I know javascript it's used for making websites interactive.",
            "Variables are like boxes. I use var for everything. And functions are blocks of code.",
            "I heard about promises, it's like async await. I just copy paste the fetch code from stack overflow.",
            "I don't really know how to do that. I just use whatever is in the tutorial."
        ]
    )
    
    # TEST CASE 2: STRONG TECHNICAL CANDIDATE
    await simulate_interview(
        "STRONG TECHNICAL CANDIDATE",
        "Backend Engineer. Python, FastAPI, PostgreSQL, AWS",
        "Backend Engineer - High Scale",
        "Technical",
        "Hard",
        [
            "For Python backend development, I prefer FastAPI due to its async support and Pydantic validation. It allows for much higher throughput compared to Flask or Django sync workers.",
            "To handle database bottlenecks, I implemented connection pooling using asyncpg, and added a Redis cache layer for read-heavy API endpoints to reduce direct DB hits by 40%.",
            "Yes, I'm very familiar with microservices. We used AWS ECS to deploy containerized services, communicating via Kafka event streams for asynchronous processing, ensuring decoupling and high availability."
        ]
    )
    
    # TEST CASE 3: HR INTERVIEW
    await simulate_interview(
        "HR INTERVIEW",
        "Software Engineer. 5 years experience.",
        "Team Lead",
        "HR",
        "Medium",
        [
            "I communicate well with my team. We have standups every day.",
            "Once we had a disagreement on a tech stack. I talked to the other dev and we just picked one.",
            "I'm a good leader because people listen to me and I get things done on time."
        ]
    )

if __name__ == "__main__":
    asyncio.run(main())
